//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Property_Service = new HashSet<Property_Service>();
        }
    
        public int ID { get; set; }
        public string Service_Name { get; set; }
    
        public virtual ICollection<Property_Service> Property_Service { get; set; }
    }
}
